spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: musicserver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#    设置文件上传最大限制
  servlet:
    multipart:
#      单个文件上传最大限制
      max-file-size: 100MB
#      总文件大小限制
      max-request-size: 2000MB
server:
  port: 9999


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.musicserver.entity
  configuration:
    map-underscore-to-camel-case: true
